version: '3'
services:
  node:
    build:
      context: .
    volumes:
      - ./:/src
    expose:
      - 8080
    ports:
      - 8080:8080
    working_dir: /src
    command: bash -c "npm install && npm start"

