version: '3'
services:
  node:
    build:
      context: .
    volumes:
      - ./:/src
      - /src/node_modules
    expose:
      - 8080
    ports:
      - 8080:8080
    working_dir: /src
    command: npm start

